# Generated by Django 4.1.7 on 2023-03-31 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
        ('contatos', '0004_contato_foto'),
    ]

    operations = [
    ]
